// flow-typed signature: c9843d267891842b5baddac0f87031f2
// flow-typed version: <<STUB>>/lambda-local_vashiina/lambda-local#316f6c743f6305385655b00db7d8349dac174c1c/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lambda-local'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lambda-local' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lambda-local/event-samples/custom' {
  declare module.exports: any;
}

declare module 'lambda-local/event-samples/dynamodb-update' {
  declare module.exports: any;
}

declare module 'lambda-local/event-samples/kinesis' {
  declare module.exports: any;
}

declare module 'lambda-local/event-samples/s3-put' {
  declare module.exports: any;
}

declare module 'lambda-local/examples/custom' {
  declare module.exports: any;
}

declare module 'lambda-local/examples/index' {
  declare module.exports: any;
}

declare module 'lambda-local/lib/context' {
  declare module.exports: any;
}

declare module 'lambda-local/lib/lambdalocal' {
  declare module.exports: any;
}

declare module 'lambda-local/lib/utils' {
  declare module.exports: any;
}

declare module 'lambda-local/test/events/test-event' {
  declare module.exports: any;
}

declare module 'lambda-local/test/functs/test-func-awsprofile' {
  declare module.exports: any;
}

declare module 'lambda-local/test/functs/test-func-fail' {
  declare module.exports: any;
}

declare module 'lambda-local/test/functs/test-func-mocking' {
  declare module.exports: any;
}

declare module 'lambda-local/test/functs/test-func-timeout' {
  declare module.exports: any;
}

declare module 'lambda-local/test/functs/test-func' {
  declare module.exports: any;
}

declare module 'lambda-local/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lambda-local/event-samples/custom.js' {
  declare module.exports: $Exports<'lambda-local/event-samples/custom'>;
}
declare module 'lambda-local/event-samples/dynamodb-update.js' {
  declare module.exports: $Exports<'lambda-local/event-samples/dynamodb-update'>;
}
declare module 'lambda-local/event-samples/kinesis.js' {
  declare module.exports: $Exports<'lambda-local/event-samples/kinesis'>;
}
declare module 'lambda-local/event-samples/s3-put.js' {
  declare module.exports: $Exports<'lambda-local/event-samples/s3-put'>;
}
declare module 'lambda-local/examples/custom.js' {
  declare module.exports: $Exports<'lambda-local/examples/custom'>;
}
declare module 'lambda-local/examples/index.js' {
  declare module.exports: $Exports<'lambda-local/examples/index'>;
}
declare module 'lambda-local/index' {
  declare module.exports: $Exports<'lambda-local'>;
}
declare module 'lambda-local/index.js' {
  declare module.exports: $Exports<'lambda-local'>;
}
declare module 'lambda-local/lib/context.js' {
  declare module.exports: $Exports<'lambda-local/lib/context'>;
}
declare module 'lambda-local/lib/lambdalocal.js' {
  declare module.exports: $Exports<'lambda-local/lib/lambdalocal'>;
}
declare module 'lambda-local/lib/utils.js' {
  declare module.exports: $Exports<'lambda-local/lib/utils'>;
}
declare module 'lambda-local/test/events/test-event.js' {
  declare module.exports: $Exports<'lambda-local/test/events/test-event'>;
}
declare module 'lambda-local/test/functs/test-func-awsprofile.js' {
  declare module.exports: $Exports<'lambda-local/test/functs/test-func-awsprofile'>;
}
declare module 'lambda-local/test/functs/test-func-fail.js' {
  declare module.exports: $Exports<'lambda-local/test/functs/test-func-fail'>;
}
declare module 'lambda-local/test/functs/test-func-mocking.js' {
  declare module.exports: $Exports<'lambda-local/test/functs/test-func-mocking'>;
}
declare module 'lambda-local/test/functs/test-func-timeout.js' {
  declare module.exports: $Exports<'lambda-local/test/functs/test-func-timeout'>;
}
declare module 'lambda-local/test/functs/test-func.js' {
  declare module.exports: $Exports<'lambda-local/test/functs/test-func'>;
}
declare module 'lambda-local/test/test.js' {
  declare module.exports: $Exports<'lambda-local/test/test'>;
}
