// flow-typed signature: a4f3bdd64b80a78343df283fcc8cb05d
// flow-typed version: <<STUB>>/node-riffraff-artefact_v^2.0.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-riffraff-artefact'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-riffraff-artefact' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-riffraff-artefact/dist/lib/util' {
  declare module.exports: any;
}

declare module 'node-riffraff-artefact/dist/riffraff-artefact' {
  declare module.exports: any;
}

declare module 'node-riffraff-artefact/dist/settings' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-riffraff-artefact/dist/lib/util.js' {
  declare module.exports: $Exports<'node-riffraff-artefact/dist/lib/util'>;
}
declare module 'node-riffraff-artefact/dist/riffraff-artefact.js' {
  declare module.exports: $Exports<'node-riffraff-artefact/dist/riffraff-artefact'>;
}
declare module 'node-riffraff-artefact/dist/settings.js' {
  declare module.exports: $Exports<'node-riffraff-artefact/dist/settings'>;
}
