// flow-typed signature: 492c8479624cf3f2b854e6bbb816fad5
// flow-typed version: <<STUB>>/replace-x_v^1.1.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'replace-x'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'replace-x' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'replace-x/bin/replace-x' {
  declare module.exports: any;
}

declare module 'replace-x/bin/search-x' {
  declare module.exports: any;
}

declare module 'replace-x/bin/shared-options-x' {
  declare module.exports: any;
}

declare module 'replace-x/test/paths' {
  declare module.exports: any;
}

declare module 'replace-x/test/sanity' {
  declare module.exports: any;
}

// Filename aliases
declare module 'replace-x/bin/replace-x.js' {
  declare module.exports: $Exports<'replace-x/bin/replace-x'>;
}
declare module 'replace-x/bin/search-x.js' {
  declare module.exports: $Exports<'replace-x/bin/search-x'>;
}
declare module 'replace-x/bin/shared-options-x.js' {
  declare module.exports: $Exports<'replace-x/bin/shared-options-x'>;
}
declare module 'replace-x/index' {
  declare module.exports: $Exports<'replace-x'>;
}
declare module 'replace-x/index.js' {
  declare module.exports: $Exports<'replace-x'>;
}
declare module 'replace-x/test/paths.js' {
  declare module.exports: $Exports<'replace-x/test/paths'>;
}
declare module 'replace-x/test/sanity.js' {
  declare module.exports: $Exports<'replace-x/test/sanity'>;
}
