// flow-typed signature: 4d3379abb31ca1f89e24b588e86efb9c
// flow-typed version: <<STUB>>/standard-flow_v^1.0.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'standard-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'standard-flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'standard-flow/bin/cmd' {
  declare module.exports: any;
}

declare module 'standard-flow/options' {
  declare module.exports: any;
}

declare module 'standard-flow/test/api' {
  declare module.exports: any;
}

declare module 'standard-flow/test/cmd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'standard-flow/bin/cmd.js' {
  declare module.exports: $Exports<'standard-flow/bin/cmd'>;
}
declare module 'standard-flow/index' {
  declare module.exports: $Exports<'standard-flow'>;
}
declare module 'standard-flow/index.js' {
  declare module.exports: $Exports<'standard-flow'>;
}
declare module 'standard-flow/options.js' {
  declare module.exports: $Exports<'standard-flow/options'>;
}
declare module 'standard-flow/test/api.js' {
  declare module.exports: $Exports<'standard-flow/test/api'>;
}
declare module 'standard-flow/test/cmd.js' {
  declare module.exports: $Exports<'standard-flow/test/cmd'>;
}
