// @flow

import { fetchConfig } from '../lib/config'
import { uploadFiles } from '../lib/S3ToSalesforceUploader'
import { authenticate } from '../lib/salesforceAuthenticator'
import type { uploadDownload } from '../lib/config'
import type { UploadInfo } from '../lib/S3ToSalesforceUploader'
import moment from 'moment'
import { getDeliveryDate } from './WeeklyInput'
import type { WeeklyInput } from './WeeklyInput'

function buildSourceAndDestination (upDown: uploadDownload, destFileName: string, sourceFileName: string): UploadInfo {
  return {
    source: {
      bucket: upDown.uploadFolder.bucket,
      prefix: upDown.uploadFolder.prefix + sourceFileName
    },
    destination: {
      fileName: destFileName,
      sfDescription: `Weekly fulfilment file ${destFileName}`,
      sfFolder: {
        folderId: upDown.uploadFolder.folderId,
        name: upDown.uploadFolder.name
      }
    }
  }
}

/**
 * Upload Guardian Weekly fulfilment files from S3 to Salesforce Document. S3 files are generated by a
 * separate step function. Upload is triggered automatically on schedule.
 */
export async function handler (input: WeeklyInput) {
  const deliveryDate = getDeliveryDate(input)
  const sfFormattedDeliveryDate = deliveryDate.format('DD_MM_YYYY')
  console.log(`Uploading Guardian Weekly issue ${sfFormattedDeliveryDate} to Salesforce...`)
  const config = await fetchConfig()
  const salesforce = await authenticate(config)
  const uploadTimeStamp = moment().format('DDMMYYYY_HH')
  const sourceFileName = `${deliveryDate.format('YYYY-MM-DD')}_WEEKLY.csv`
  const s3ToSfName = (prefix: string) => `${prefix}_${sfFormattedDeliveryDate}_${uploadTimeStamp}.csv`
  const filesToUpload = [
    buildSourceAndDestination(config.fulfilments.weekly.NZ, s3ToSfName('GWNZ'), sourceFileName),
    buildSourceAndDestination(config.fulfilments.weekly.AU, s3ToSfName('GWAU'), sourceFileName),
    buildSourceAndDestination(config.fulfilments.weekly.CA, s3ToSfName('GWCA'), sourceFileName),
    buildSourceAndDestination(config.fulfilments.weekly.CAHAND, s3ToSfName('GWCA_HAND'), sourceFileName),
    buildSourceAndDestination(config.fulfilments.weekly.ROW, s3ToSfName('GWRW'), sourceFileName),
    buildSourceAndDestination(config.fulfilments.weekly.UK, s3ToSfName('GWUK'), sourceFileName),
    buildSourceAndDestination(config.fulfilments.weekly.US, s3ToSfName('GWUS'), sourceFileName),
    buildSourceAndDestination(config.fulfilments.weekly.VU, s3ToSfName('GWVA'), sourceFileName),
    buildSourceAndDestination(config.fulfilments.weekly.EU, s3ToSfName('GWEU'), sourceFileName)
  ]
  const result = await uploadFiles(filesToUpload, salesforce)
  console.log(`Successfully uploaded Guardian Weekly issue ${sfFormattedDeliveryDate} to Salesforce`)
  return result
}
